name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Setup Heroku credentials
        run: |
          cat > ~/.netrc <<EOF
          machine api.heroku.com
            login ${{secrets.HEROKU_EMAIL}}
            password ${{secrets.HEROKU_PASSWORD}}
          machine git.heroku.com
            login ${{secrets.HEROKU_EMAIL}}
            password ${{secrets.HEROKU_PASSWORD}}
          EOF
          chmod 600 ~/.netrc

      - name: Setup heroku remote
        run: heroku git:remote -a ${{secrets.HEROKU_APP_NAME}}

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: false
          branch: "master"